"""'initial_migration2'

Revision ID: 0502a48a8a05
Revises: 54e5eb3fe847
Create Date: 2024-04-21 14:40:12.302230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0502a48a8a05"
down_revision: Union[str, None] = "54e5eb3fe847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
